#!/bin/bash
sudo yum update -y
sudo yum install -y httpd
sudo echo '<html><body><h1>Hello from EC2 Instance1 </h1></body></html>' > /var/www/html/index.html
sudo systemctl start httpd
sudo systemctl enable httpd
